CREATE TABLE public.tarrasq_tasks (
	pk TEXT NOT NULL,
	sk TEXT NOT NULL,
	gsis_pk___shard INT NOT NULL DEFAULT 0,
	gsip_pk___perimeter INT NOT NULL DEFAULT 0,
	gsi1_pk___tenant TEXT,
	gsi2_pk__pk___tenant__task_name TEXT,
	gsi2_sk___tenant__task_id TEXT,	
	jsondata jsonb,
	binpb bytea,
	protocol BIGINT NOT NULL,
	"application" BIGINT NOT NULL,
	created TIMESTAMP NOT NULL,
	updated TIMESTAMP,
	deleted TIMESTAMP,
	expiry_unix_second BIGINT,
	monotonic BIGINT NOT NULL,
	owner_blob jsonb,
	genesis_blob jsonb,
	principal_blob jsonb,
	request_blob jsonb,
	owner_pb bytea,
	genesis_pb bytea,
	principal_pb bytea,
	request_pb bytea,
	PRIMARY KEY (pk, sk)
);

CREATE TABLE public.tarrasq_runs (
	pk TEXT NOT NULL,
	sk TEXT NOT NULL,
	gsis_pk___shard INT NOT NULL DEFAULT 0,
	gsip_pk___perimeter INT NOT NULL DEFAULT 0,
	gsi1_pk___tenant TEXT,
	jsondata jsonb,
	binpb bytea,
	protocol BIGINT NOT NULL,
	"application" BIGINT NOT NULL,
	created TIMESTAMP NOT NULL,
	updated TIMESTAMP,
	deleted TIMESTAMP,
	expiry_unix_second BIGINT,
	monotonic BIGINT NOT NULL DEFAULT 0,
	owner_blob jsonb,
	genesis_blob jsonb,
	principal_blob jsonb,
	request_blob jsonb,
	owner_pb bytea,
	genesis_pb bytea,
	principal_pb bytea,
	request_pb bytea,	
	PRIMARY KEY (pk, sk)
);

CREATE TABLE public.tarrasq_dispatch (
	pk TEXT NOT NULL,
	sk TEXT NOT NULL,
	gsis_pk___shard INT NOT NULL DEFAULT 0,
	gsip_pk___perimeter INT NOT NULL DEFAULT 0,	
	gsi1_pk___tenant TEXT,
	jsondata jsonb,
	binpb bytea,
	protocol BIGINT NOT NULL,
	"application" BIGINT NOT NULL,
	created TIMESTAMP NOT NULL,
	updated TIMESTAMP,
	deleted TIMESTAMP,
	expiry_unix_second BIGINT,
	monotonic BIGINT NOT NULL DEFAULT 0,
	owner_blob jsonb,
	genesis_blob jsonb,
	principal_blob jsonb,
	request_blob jsonb,
	owner_pb bytea,
	genesis_pb bytea,
	principal_pb bytea,
	request_pb bytea,
	PRIMARY KEY (pk, sk)
);

 GRANT USAGE ON SCHEMA public TO fes_user;
 GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO fes_user;